"""initial_rsl_tables

Revision ID: d36deed3a465
Revises: 
Create Date: 2026-03-20 19:15:28.829269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd36deed3a465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=False),
    sa.Column('claimed_diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_claim_id'), 'claim', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claim_facility_id'), 'claim', ['facility_id'], unique=False)
    op.create_index(op.f('ix_claim_job_id'), 'claim', ['job_id'], unique=False)
    op.create_index(op.f('ix_claim_patient_id'), 'claim', ['patient_id'], unique=False)
    op.create_index(op.f('ix_claim_user_id'), 'claim', ['user_id'], unique=False)
    op.create_table('facilityweeklymetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('claim_volume', sa.Integer(), nullable=False),
    sa.Column('avg_anomaly_score', sa.Float(), nullable=False),
    sa.Column('flagged_claims', sa.Integer(), nullable=False),
    sa.Column('high_severity_count', sa.Integer(), nullable=False),
    sa.Column('medium_severity_count', sa.Integer(), nullable=False),
    sa.Column('low_severity_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilityweeklymetric_facility_id'), 'facilityweeklymetric', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facilityweeklymetric_week_start_date'), 'facilityweeklymetric', ['week_start_date'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('processed_claims', sa.Integer(), nullable=False),
    sa.Column('failed_claims', sa.Integer(), nullable=False),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_job_id'), 'job', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    op.create_table('patienttrajectory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visit_sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trajectory_anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_trajectory_anomaly', sa.Boolean(), nullable=True),
    sa.Column('per_visit_errors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('most_anomalous_visit_index', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patienttrajectory_patient_id'), 'patienttrajectory', ['patient_id'], unique=True)
    op.create_table('cbcdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.Column('sex_encoded', sa.Integer(), nullable=False),
    sa.Column('HGB', sa.Float(), nullable=False),
    sa.Column('HCT', sa.Float(), nullable=False),
    sa.Column('MCV', sa.Float(), nullable=False),
    sa.Column('MCHC', sa.Float(), nullable=False),
    sa.Column('NEU', sa.Float(), nullable=False),
    sa.Column('LYM', sa.Float(), nullable=False),
    sa.Column('EOS', sa.Float(), nullable=False),
    sa.Column('BAS', sa.Float(), nullable=False),
    sa.Column('MON', sa.Float(), nullable=False),
    sa.Column('PLT', sa.Float(), nullable=False),
    sa.Column('length_of_stay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cbcdata_claim_id'), 'cbcdata', ['claim_id'], unique=False)
    op.create_table('fraudflag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flag_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('predicted_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('predicted_diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('diagnosis_confidence', sa.Float(), nullable=True),
    sa.Column('insufficient_history', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraudflag_claim_id'), 'fraudflag', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraudflag_claim_id'), table_name='fraudflag')
    op.drop_table('fraudflag')
    op.drop_index(op.f('ix_cbcdata_claim_id'), table_name='cbcdata')
    op.drop_table('cbcdata')
    op.drop_index(op.f('ix_patienttrajectory_patient_id'), table_name='patienttrajectory')
    op.drop_table('patienttrajectory')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_job_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_facilityweeklymetric_week_start_date'), table_name='facilityweeklymetric')
    op.drop_index(op.f('ix_facilityweeklymetric_facility_id'), table_name='facilityweeklymetric')
    op.drop_table('facilityweeklymetric')
    op.drop_index(op.f('ix_claim_user_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_patient_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_job_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_facility_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_claim_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
